### ISSUE TITLE
More than one Google Gallery on one page

### ISSUE THREAD

**Issue by Enkuryo** [nitsan-technologies/ns_gallery#3]
Hey,

is it possible to use the Google Gallery more than once on one page?
It seems that there are errors if I click on one image to open the preview.

The preview window position does not match with the image I clicked on or the height of the preview window is not set correctly and the image is not shown.

Thanks in advance.

**Comment by nitsan-technologies** [comment]
Hello @Enkuryo 

Thanks for the message. Yes, it's possible. But somehow some issue in that. We have resolved that now. Please download the latest version from TER.

Thanks!
Jignesh
