### ISSUE TITLE
Preview issue with loading more images

### ISSUE THREAD

**Issue by Enkuryo** [nitsan-technologies/ns_gallery#5]
Hey,

I just updated to v2.0.4 but there still seems to be an issue. If you look at the page [https://motorsport.adac-sh.de/meisterschaften/adac-nmx-cup/adac-nmx-cup](https://motorsport.adac-sh.de/meisterschaften/adac-nmx-cup/adac-nmx-cup), click on the first "Mehr laden" button and then click on an image that was newly loaded, the preview is at the top of the page and there is no image inside:

![image](https://user-images.githubusercontent.com/9133037/177556526-28ee7add-5921-4a6b-9248-5f050228b9b8.png)

Would you mind have a look?

**Comment by nitsan-technologies** [comment]
Hello @Enkuryo 
Greetings of the day!

Thanks for the message and the issue. We have resolved this issue and released the new version of this. Please update your extension. 

Thanks!
Team NITSAN
